XOR-42[FIX] Ensure Menu Settings opens after clicking bottom menu
Fliplet/fliplet-widget-menu-manager pull request #50
Opened 2022-05-08 07:36 UTC by anshukdutt

### Product areas affected

Fliplet Widget menu manager, interface.js
### What does this PR do?

Menu Links opens after clicking Bottom menu and bottom menu icons

### JIRA ticket

[JIRA ticket](https://weboo.atlassian.net/browse/XOR-42)

### Result

[Screen Recordings](https://api.media.atlassian.com/file/74b0370f-3aab-47d3-aeb8-f914aee68957/artifact/video_1280.mp4/binary?client=435f5956-a841-4ea9-80ca-d94a2672bba6&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI0MzVmNTk1Ni1hODQxLTRlYTktODBjYS1kOTRhMjY3MmJiYTYiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjljYTBmN2Y3LWUwYmQtNDhhMy1hYjM4LTJhZDY4MmQzNTYzYiI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZToyZGNkMThkNy05MDJkLTQxNDYtODZjOC1mYWEzZjQ0NTllNWYiOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6NzRiMDM3MGYtM2FhYi00N2QzLWFlYjgtZjkxNGFlZTY4OTU3IjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOjg5ZmQ1ZjgzLWE5ODQtNGY5NC04NTVhLWIzZGJjOGU0OTJjNSI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTo5NTIwODgxNS1lZmJjLTQyYTItYmRjNy0zZDBiNWYxOGU0ODMiOlsicmVhZCJdfSwiZXhwIjoxNjUxOTkyOTY2LCJuYmYiOjE2NTE5OTIwMDZ9.LK2ep5vrloyllBi8v_rFVymDjlfnigVsyfUegJQCqHA)

### Checklist

None
### Testing instructions

None
### Deployment instructions

None
### Author concerns

None

2022-05-09 06:11 UTC, anerib approved these changes
LGTM

2022-05-17 06:30 UTC, tonytlwu requested changes

2022-05-17 06:30 UTC, tonytlwu commented on js/interface.js
> +      $('.nav.nav-tabs li a[aria-controls="menu-manager"]').trigger('click');
See https://getbootstrap.com/docs/3.3/javascript/#tabs

![image](https://user-images.githubusercontent.com/290733/168743846-7cf676a3-c691-4192-b468-a308efebcc6a.png)

This is how you use Bootstrap's API to select a tab by name. Please use the `href` target, not the ARIA accessibility attribute, and use the Bootstrap API.

2022-05-23 09:37 UTC, tonytlwu requested changes
Incorrect usage of Bootstrap API. See previous review comment.

2022-05-25 09:25 UTC, anshukdutt commented
Hi @tonytlwu, 
As suggested $(`.nav.nav-tabs a[href='#${eventData.data.tab}']`).tab('show'), I used _.tab('show')_ , but its not working (Menu Links gets active but it keeps on loading)
On the other hand Using _.trigger('click')_ working fine. 
Can you suggest

2022-05-26 09:59 UTC, tonytlwu commented
@anshukdutt We can stick with `.trigger('click')` for now. It looks like there's another instance in the same file that uses the same pattern.

2022-05-26 10:00 UTC, tonytlwu approved these changes

2022-05-26 10:00 UTC, merged