XOR-851 [FIX] Ensure A random custom menu link is not deleted along with the one you originally intended to delete
Fliplet/fliplet-widget-menu-manager pull request #55
Opened 2023-01-25 10:40 UTC by NikitaJadhavXoriant

**Product areas affected**

Studio -> Menu Options -> Menu Links -> Custom menu

**What does this PR do?**

Implemented code to prevent deleting of custom menu link along with the one you originally intended to delete.

**JIRA ticket**

[click here](https://weboo.atlassian.net/browse/XOR-851)

**Result**

https://user-images.githubusercontent.com/108272606/214542446-6578a8e4-0807-4d6a-b361-a2104d455d9f.mp4

**Checklist**

None

**Testing instructions**

None

**Deployment instructions**

None

**Author concerns**

None

2023-01-25 11:36 UTC, yogeshmsharma-xoriant approved these changes
looks ok

2023-01-25 14:47 UTC, tonytlwu requested changes

2023-01-25 14:47 UTC, tonytlwu commented on js/interface.js
> +          var currentMenuItem = _.findIndex(currentMenuItems, function(item) { return item.id === id; });
This doesn't need to run unless `if` passes

2023-01-26 09:31 UTC, tonytlwu approved these changes

2023-01-26 09:32 UTC, merged